In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [21]:
result = pd.read_csv("../results/time_preprocessing.csv")
result

                      Phase  Duration (seconds)            Timestamp
0  PDF Extraction (docling)           3898.3251  2026-04-17 11:50:26
1              PDF Chunking              6.0412  2026-04-17 11:50:32
2    Total Pipeline Runtime           3904.3663  2026-04-17 11:50:32

In [22]:
result = pd.read_csv("../results/time_baseline.csv")
result

                      Phase  Duration (seconds)            Timestamp
0          Index Build/Load            265.7124  2026-04-17 14:04:24
1  Component Initialization              0.2048  2026-04-17 14:04:24
2    Data Loading/Filtering              0.0083  2026-04-17 14:04:24
3         Single Query Test              8.9728  2026-04-17 14:04:33
4           Full Evaluation             59.5500  2026-04-17 14:05:33
5    Total Pipeline Runtime            334.4483  2026-04-17 14:05:33

In [2]:
result = pd.read_csv("../../experiments_results.csv")

In [3]:
result

,Experiment Name,System Type,Timestamp,Total Runtime (s),Eval Runtime (s),Retrieval precision@1,Retrieval precision@3,Retrieval precision@5,Retrieval recall@1,Retrieval recall@3,...,Retrieval map,Retrieval mrr,Generation exact_match,Generation contains_match,Generation token_f1,Generation bleu,Generation rouge1,Generation rouge2,Generation rougeL,Generation semantic_similarity
0,1_Baseline,Baseline,2026-04-15 13:54:17,16.59,0.75,0.5,0.3333,0.2,0.5,1.0,...,0.6667,0.6667,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,3_QueryTech_multi_query,Advanced,2026-04-15 14:02:19,12.04,2.63,0.0,0.0000,0.0,0.0,0.0,...,0.0000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3_QueryTech_rag_fusion,Advanced,2026-04-15 14:02:31,11.91,2.49,0.0,0.0000,0.0,0.0,0.0,...,0.0000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3_QueryTech_step_back,Advanced,2026-04-15 14:02:41,10.34,1.06,0.0,0.0000,0.0,0.0,0.0,...,0.0000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,3_QueryTech_hyde,Advanced,2026-04-15 14:03:08,26.23,17.13,0.0,0.1667,0.1,0.0,0.5,...,0.2500,0.2500,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,3_QueryTech_query_decomposition,Advanced,2026-04-15 14:03:20,11.78,2.94,0.0,0.0000,0.0,0.0,0.0,...,0.0000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,3_QueryTech_query_rewriting,Advanced,2026-04-15 14:03:33,13.42,1.20,0.0,0.0000,0.0,0.0,0.0,...,0.0000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,3_QueryTech_query_expansion,Advanced,2026-04-15 14:03:45,12.46,2.98,0.0,0.0000,0.0,0.0,0.0,...,0.0000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,4_Prompting_standard,Advanced,2026-04-15 14:03:57,11.10,2.57,0.0,0.0000,0.0,0.0,0.0,...,0.0000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,4_Prompting_few_shot,Advanced,2026-04-15 14:04:08,11.47,2.47,0.0,0.0000,0.0,0.0,0.0,...,0.0000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,4_Prompting_role,Advanced,2026-04-15 14:04:19,11.28,2.46,0.0,0.0000,0.0,0.0,0.0,...,0.0000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,4_Prompting_cot,Advanced,2026-04-15 14:04:31,11.88,2.47,0.0,0.0000,0.0,0.0,0.0,...,0.0000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,4_Prompting_ensemble,Advanced,2026-04-15 14:04:43,11.37,2.45,0.0,0.0000,0.0,0.0,0.0,...,0.0000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,5_Multimodal_Retrieval,Advanced,2026-04-15 14:05:10,27.65,0.64,0.5,0.3333,0.2,0.5,1.0,...,0.6667,0.6667,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0